# AI News Bot 配置文件
# 请根据实际情况填写各项配置信息

# 飞书机器人配置 (支持多个群组推送)
lark:
  # 主要群组
  primary:
    api_url: "https://open.feishu.cn/open-apis/bot/v2/hook/25a381cd-e91a-496c-9117-9c77b00d7613"
    api_secret: "WYDI1R5kaqfQpTxMUBzMbfwBJcZgw4e6"
    name: "主群组"
  # 第二个群组 (请替换为你的第二个群组信息)
  secondary:
    api_url: "https://open.feishu.cn/open-apis/bot/v2/hook/11d9e8a8-08f4-4c05-b324-74ebb0a4ff92"
    api_secret: "WYDI1R5kaqfQpTxMUBzMbfwBJcZgw4e6"
    name: "备用群组"

# API 配置
apis:
  # AutoAgents AI 配置
  autoagentsai:
    # 统一AI处理 Agent (JSON格式翻译+总结)
    ai_agent:
      agent_id: "4cd27eeaf0984196a2bc005f0bde4b70"
      personal_auth_key: "7217394b7d3e4becab017447adeac239"
      personal_auth_secret: "f4Ziua6B0NexIMBGj1tQEVpe62EhkCWB"

# Supabase 数据库配置
supabase:
  url: "https://bvgdasmmglbecqnkmpsd.supabase.co"
  anon_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2Z2Rhc21tZ2xiZWNxbmttcHNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDc3MDAsImV4cCI6MjA3MTAyMzcwMH0.IetyyxTiDOXjBAWETD51Sn3riyp5IcVUBmU9vi_k9DA"


# 数据库表配置
database:
  table_name: "ai_news"
